# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            'fiveisprime'
tagline:          'the more you node...'
description:      '@fiveisprime'
url:              https://fiveisprime.github.io

author:
  name:           'Matt Hernandez'
  url:            https://fiveisprime.github.io

paginate:         3

# Custom vars
links:
  github:           https://github.com/fiveisprime
  twitter:          https://twitter.com/fiveisprime
