# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'fiveisprime'
tagline:          'the more you node...'
description:      '@fiveisprime'
url:              https://fiveisprime.github.io

author:
  name:           'Matt Hernandez'
  url:            https://twitter.com/fiveisprime

paginate:         3

# Custom vars
github:
  home:           https://github.com/fiveisprime
